
class LocalizationService:
    _instance = None
    
    # Supported languages
    LANGUAGES = {
        "en": "English",
        "tr": "Türkçe",
        "de": "Deutsch",
        "fr": "Français",
        "it": "Italiano"
    }

    STRINGS = {
        "en": {
            "app_title": "Terminal FM Radio Player - Global & Local",
            "connecting": "Connecting:",
            "now_playing": "Now Playing",
            "station": "Station",
            "country": "Country",
            "genre": "Genre",
            "song": "Song",
            "volume": "Volume",
            "recording": "RECORDING",
            "no_stations": "No stations found to display.",
            "total_stations": "Total {count} stations listed.",
            "welcome_msg": "Type 'help' for commands, 'exit' to quit.",
            "unknown_command": "Unknown command: '{cmd}'. Type 'help' for help.",
            "error_executing": "Error executing command: {error}",
            "shell_error": "Shell error: {error}",
            "help_title": "COMMAND LIST",
            "cat_listing": "STATION LISTING",
            "cat_playback": "PLAYBACK",
            "cat_recording": "RECORDING",
            "cat_management": "MANAGEMENT",
            "cat_other": "OTHER",
            "cat_general": "GENERAL",
            "help_general": "help / ?            - Show this help menu",
            "exit_general": "exit / q / quit     - Exit application",
            "stopped": "radio stopped",
            "waiting_song": "waiting for song info",
            "lang_select_title": "LANGUAGE SELECTION / DİL SEÇİMİ",
            "lang_select_msg": "Please select your language / Lütfen dilinizi seçin:",
            "lang_updated": "Language updated to: {lang}",
            "sys_info_title": "System Information",
            "sys_os": "Operating System",
            "sys_python": "Python Version",
            "sys_cpu": "CPU Usage",
            "sys_ram": "System RAM",
            "sys_total_mem": "Total Usage",
            "stats_total_time": "Total Listening Time",
            "stats_total_sessions": "Total Sessions",
            "stats_top_title": "Top 10 Stations",
            "stats_no_data": "No statistics yet.",
            "id": "ID",
            "name": "Station Name",
            "fav": "Fav",
            "no": "No",
            "cmd_listele_desc": "Lists all radio stations",
            "cmd_turkiye_desc": "Lists Turkish radio stations",
            "cmd_ulkeler_desc": "Lists available countries",
            "cmd_ulke_desc": "Lists stations of a specific country",
            "cmd_turler_desc": "Lists available music genres",
            "cmd_tur_desc": "Lists stations of a specific genre",
            "cmd_ara_desc": "Search stations (name, country or genre)",
            "cmd_istatistik_desc": "Shows listening statistics",
            "cmd_durum_desc": "Shows current playback status",
            "cmd_sistem_desc": "Shows system and RAM usage info",
            "cmd_temizle_desc": "Clears the terminal screen",
            "cmd_cal_desc": "Plays a station by ID or index",
            "cmd_durdur_desc": "Stops playback",
            "cmd_ses_desc": "Changes volume level",
            "cmd_son_desc": "Plays the last played station",
            "cmd_sonraki_desc": "Plays the next station in the current list",
            "cmd_onceki_desc": "Plays the previous station in the current list",
            "cmd_karistir_desc": "Plays a random station",
            "cmd_uyku_desc": "Starts sleep timer",
            "cmd_gecmis_desc": "Shows song history",
            "cmd_favori_desc": "Adds/removes station to favorites",
            "cmd_favoriler_desc": "Lists favorite stations",
            "cmd_kaydet_desc": "Starts recording current stream",
            "cmd_kayitdur_desc": "Stops recording",
            "cmd_tema_desc": "Changes color theme",
            "cmd_kontrol_desc": "Checks station stream URLs",
            "cmd_ekle_desc": "Adds a new custom station",
            "cmd_duzenle_desc": "Edits a custom station",
            "cmd_sil_desc": "Deletes a custom station",
            "cmd_iceaktar_desc": "Adds stations from playlist file",
            "cmd_bildirim_desc": "Turns notifications on/off",
            "cmd_online_ara_desc": "Search stations via RadioBrowser",
            "cmd_online_ekle_desc": "Adds station from search results",
            "cmd_dil_desc": "Changes application language",
            "cmd_listele_hint": "Shows first 50 by default. Custom: listele -n NUMBER · All: listele --hepsi",
            "msg_not_playing": "Radio is not playing!",
            "msg_already_recording": "Already recording!",
            "msg_recording_started": "Recording started: {file}",
            "msg_recording_failed": "Could not start recording: {error}",
            "msg_no_active_record": "No active recording.",
            "msg_recording_stopped": "Recording stopped. Saved to: {path}",
            "msg_recording_stopped_simple": "Recording stopped.",
            "msg_playing": "Playing: {name}",
            "msg_stop_playing": "Playback stopped.",
            "msg_vol_set": "Volume set to: {vol}%",
            "msg_no_last_station": "No last played station record.",
            "msg_last_station_missing": "Last played station no longer exists.",
            "msg_need_list": "Please create a list first (e.g., listele, turkiye).",
            "msg_no_playing_station": "No station currently playing.",
            "msg_station_not_in_list": "Current station not found in the last list.",
            "msg_no_match": "No station found matching the criteria.",
            "msg_sleep_cancel": "Sleep timer cancelled.",
            "msg_no_sleep": "No active sleep timer.",
            "msg_sleep_set": "Sleep timer set: will stop in {min} minutes.",
            "msg_sleep_done": "Sleep timer finished, playback stopped.",
            "msg_no_history": "No song history yet.",
            "msg_recent_songs": "Recent songs:",
            "msg_fav_added": "Added to favorites: {name}",
            "msg_fav_removed": "Removed from favorites: {name}",
            "msg_station_not_found": "Station not found.",
            "msg_custom_only": "Only custom stations can be edited.",
            "msg_station_updated": "Station updated.",
            "msg_station_deleted": "Station deleted: {id}",
            "msg_station_added": "Custom station added: {name}",
            "msg_import_success": "{count} stations imported.",
            "msg_import_fail": "Could not read stations or file not found.",
            "msg_notify_on": "Desktop notifications on.",
            "msg_notify_off": "Desktop notifications off.",
            "msg_searching": "Searching...",
            "msg_search_results": "Online Search Results",
            "msg_online_add_hint": "To add: online-ekle -n <no>",
            "msg_checking": "{count} stations being checked... (This may take a while)",
            "msg_check_done": "Check complete: {success}/{total} active.",
            "msg_active": "ACTIVE",
            "msg_failed": "FAILED",
            "msg_error": "ERROR"
        },
        "tr": {
            "app_title": "Terminal FM Radyo Çalar - Türkiye & Dünya",
            "connecting": "Bağlanıyor:",
            "now_playing": "Çalıyor",
            "station": "Radyo",
            "country": "Ülke",
            "genre": "Tür",
            "song": "Şarkı",
            "volume": "Ses",
            "recording": "KAYIT YAPILIYOR",
            "no_stations": "Gösterilecek istasyon bulunamadı.",
            "total_stations": "Toplam {count} istasyon listelendi.",
            "welcome_msg": "Komutlar için 'help', çıkmak için 'exit' yazın.",
            "unknown_command": "Bilinmeyen komut: '{cmd}'. Yardım için 'help' yazın.",
            "error_executing": "Komut çalıştırılırken hata: {error}",
            "shell_error": "Shell hatası: {error}",
            "help_title": "KOMUT LİSTESİ",
            "cat_listing": "İSTASYON LİSTELEME",
            "cat_playback": "OYNATMA",
            "cat_recording": "KAYIT",
            "cat_management": "YÖNETİM",
            "cat_other": "DİĞER",
            "cat_general": "GENEL",
            "help_general": "help / ?            - Bu yardım menüsünü gösterir",
            "exit_general": "exit / q / quit     - Uygulamadan çıkar",
            "stopped": "radyo durduruldu",
            "waiting_song": "şarkı bilgisi bekleniyor",
            "lang_select_title": "DİL SEÇİMİ",
            "lang_select_msg": "Lütfen dilinizi seçin:",
            "lang_updated": "Dil güncellendi: {lang}",
            "sys_info_title": "Sistem Bilgileri",
            "sys_os": "İşletim Sistemi",
            "sys_python": "Python Sürümü",
            "sys_cpu": "CPU Kullanımı",
            "sys_ram": "Sistem RAM",
            "sys_total_mem": "Toplam Kullanım",
            "stats_total_time": "Toplam Dinleme",
            "stats_total_sessions": "Toplam Oturum",
            "stats_top_title": "Top 10 İstasyon",
            "stats_no_data": "Henüz istatistik yok.",
            "id": "ID",
            "name": "İstasyon İsmi",
            "fav": "Fav",
            "no": "No",
            "cmd_listele_desc": "Tüm radyo istasyonlarını listeler",
            "cmd_turkiye_desc": "Türkiye radyo istasyonlarını listeler",
            "cmd_ulkeler_desc": "Mevcut ülkeleri listeler",
            "cmd_ulke_desc": "Belirli bir ülkenin istasyonlarını listeler",
            "cmd_turler_desc": "Mevcut müzik türlerini listeler",
            "cmd_tur_desc": "Belirli bir müzik türündeki istasyonları listeler",
            "cmd_ara_desc": "İstasyon arar (isim, ülke veya tür)",
            "cmd_istatistik_desc": "Dinleme istatistiklerini gösterir",
            "cmd_durum_desc": "Şu anki çalma durumunu gösterir",
            "cmd_sistem_desc": "Sistem ve RAM kullanım bilgilerini gösterir",
            "cmd_temizle_desc": "Terminal ekranını temizler",
            "cmd_cal_desc": "ID veya No ile istasyon oynatır",
            "cmd_durdur_desc": "Oynatmayı durdurur",
            "cmd_ses_desc": "Ses seviyesini değiştirir",
            "cmd_son_desc": "En son çalınan istasyonu oynatır",
            "cmd_sonraki_desc": "Listedeki bir sonraki istasyona geçer",
            "cmd_onceki_desc": "Listedeki bir önceki istasyona geçer",
            "cmd_karistir_desc": "Rastgele bir istasyon çalar",
            "cmd_uyku_desc": "Uyku zamanlayıcısını başlatır",
            "cmd_gecmis_desc": "Şarkı geçmişini gösterir",
            "cmd_favori_desc": "İstasyonu favorilere ekler/çıkarır",
            "cmd_favoriler_desc": "Favori istasyonları listeler",
            "cmd_kaydet_desc": "Çalan yayını kaydetmeye başlar",
            "cmd_kayitdur_desc": "Kaydı durdurur",
            "cmd_tema_desc": "Renk temasını değiştirir",
            "cmd_kontrol_desc": "İstasyon akış URL'lerini kontrol eder",
            "cmd_ekle_desc": "Yeni özel istasyon ekler",
            "cmd_duzenle_desc": "Özel istasyonu düzenler",
            "cmd_sil_desc": "Özel istasyonu siler",
            "cmd_iceaktar_desc": "Playlist dosyasından istasyon ekler",
            "cmd_bildirim_desc": "Bildirimleri açar/kapatır",
            "cmd_online_ara_desc": "RadioBrowser üzerinden istasyon arar",
            "cmd_online_ekle_desc": "Arama sonucundan istasyon ekler",
            "cmd_dil_desc": "Uygulama dilini değiştirir",
            "cmd_listele_hint": "Varsayılan ilk 50 gösterir. Özel adet: listele -n SAYI · Tümü: listele --hepsi",
            "msg_not_playing": "Radyo çalmıyor!",
            "msg_already_recording": "Zaten kayıt yapılıyor!",
            "msg_recording_started": "Kayıt başladı: {file}",
            "msg_recording_failed": "Kayıt başlatılamadı: {error}",
            "msg_no_active_record": "Aktif kayıt yok.",
            "msg_recording_stopped": "Kayıt durduruldu. Şuraya kaydedildi: {path}",
            "msg_recording_stopped_simple": "Kayıt durduruldu.",
            "msg_playing": "Çalınıyor: {name}",
            "msg_stop_playing": "Oynatma durduruldu.",
            "msg_vol_set": "Ses seviyesi ayarlandı: %{vol}",
            "msg_no_last_station": "Son çalınan istasyon kaydı yok.",
            "msg_last_station_missing": "Son çalınan istasyon artık bulunmuyor.",
            "msg_need_list": "Önce bir liste oluşturun (örn: listele, turkiye).",
            "msg_no_playing_station": "Şu an çalan bir istasyon yok.",
            "msg_station_not_in_list": "Mevcut istasyon son listede bulunamadı.",
            "msg_no_match": "Kriterlere uygun istasyon bulunamadı.",
            "msg_sleep_cancel": "Uyku zamanlayıcısı iptal edildi.",
            "msg_no_sleep": "Aktif uyku zamanlayıcısı yok.",
            "msg_sleep_set": "Uyku zamanlayıcısı ayarlandı: {min} dakika sonra duracak.",
            "msg_sleep_done": "Uyku zamanlayıcısı süresi doldu, oynatma durduruldu.",
            "msg_no_history": "Henüz şarkı geçmişi yok.",
            "msg_recent_songs": "Son çalınan şarkılar:",
            "msg_fav_added": "Favorilere eklendi: {name}",
            "msg_fav_removed": "Favorilerden çıkarıldı: {name}",
            "msg_station_not_found": "İstasyon bulunamadı.",
            "msg_custom_only": "Yalnızca özel istasyonlar düzenlenebilir.",
            "msg_station_updated": "İstasyon güncellendi.",
            "msg_station_deleted": "İstasyon silindi: {id}",
            "msg_station_added": "Özel istasyon eklendi: {name}",
            "msg_import_success": "{count} istasyon içe aktarıldı.",
            "msg_import_fail": "İstasyon okunamadı veya dosya bulunamadı.",
            "msg_notify_on": "Masaüstü bildirimleri açıldı.",
            "msg_notify_off": "Masaüstü bildirimleri kapatıldı.",
            "msg_searching": "Aranıyor...",
            "msg_search_results": "Online Arama Sonuçları",
            "msg_online_add_hint": "Eklemek için: online-ekle -n <no>",
            "msg_checking": "{count} istasyon kontrol ediliyor... (Zaman alabilir)",
            "msg_check_done": "Kontrol tamamlandı: {success}/{total} aktif.",
            "msg_active": "AKTİF",
            "msg_failed": "BAŞARISIZ",
            "msg_error": "HATA"
        },
        "de": {
            "app_title": "Terminal FM Radio Player - Global & Lokal",
            "connecting": "Verbinden:",
            "now_playing": "Läuft gerade",
            "station": "Sender",
            "country": "Land",
            "genre": "Genre",
            "song": "Lied",
            "volume": "Lautstärke",
            "recording": "AUFNAHME",
            "no_stations": "Keine Stationen zum Anzeigen gefunden.",
            "total_stations": "Insgesamt {count} Stationen aufgelistet.",
            "welcome_msg": "Geben Sie 'help' für Befehle ein, 'exit' zum Beenden.",
            "unknown_command": "Unbekannter Befehl: '{cmd}'. Geben Sie 'help' für Hilfe ein.",
            "error_executing": "Fehler beim Ausführen des Befehls: {error}",
            "shell_error": "Shell-Fehler: {error}",
            "help_title": "BEFEHLSLISTE",
            "cat_listing": "SENDERLISTE",
            "cat_playback": "WIEDERGABE",
            "cat_recording": "AUFNAHME",
            "cat_management": "VERWALTUNG",
            "cat_other": "SONSTIGES",
            "cat_general": "ALLGEMEIN",
            "help_general": "help / ?            - Diese Hilfe anzeigen",
            "exit_general": "exit / q / quit     - Anwendung beenden",
            "stopped": "Radio gestoppt",
            "waiting_song": "Warten auf Liedinformationen",
            "lang_select_title": "SPRACHAUSWAHL",
            "lang_select_msg": "Bitte wählen Sie Ihre Sprache:",
            "lang_updated": "Sprache aktualisiert auf: {lang}",
            "sys_info_title": "Systeminformationen",
            "sys_os": "Betriebssystem",
            "sys_python": "Python-Version",
            "sys_cpu": "CPU-Auslastung",
            "sys_ram": "System-RAM",
            "sys_total_mem": "Gesamtverbrauch",
            "stats_total_time": "Gesamte Hörzeit",
            "stats_total_sessions": "Gesamtsitzungen",
            "stats_top_title": "Top 10 Sender",
            "stats_no_data": "Noch keine Statistiken.",
            "id": "ID",
            "name": "Sendername",
            "fav": "Fav",
            "no": "Nr",
            "cmd_listele_desc": "Listet alle Radiosender auf",
            "cmd_turkiye_desc": "Listet türkische Radiosender auf",
            "cmd_ulkeler_desc": "Listet verfügbare Länder auf",
            "cmd_ulke_desc": "Listet Sender eines bestimmten Landes auf",
            "cmd_turler_desc": "Listet verfügbare Musikrichtungen auf",
            "cmd_tur_desc": "Listet Sender einer bestimmten Richtung auf",
            "cmd_ara_desc": "Suche nach Sendern (Name, Land oder Genre)",
            "cmd_istatistik_desc": "Zeigt Hörstatistiken an",
            "cmd_durum_desc": "Zeigt den aktuellen Wiedergabestatus an",
            "cmd_sistem_desc": "Zeigt System- und RAM-Nutzung an",
            "cmd_temizle_desc": "Leert den Terminal-Bildschirm",
            "cmd_cal_desc": "Spielt einen Sender nach ID oder Index ab",
            "cmd_durdur_desc": "Stoppt die Wiedergabe",
            "cmd_ses_desc": "Ändert die Lautstärke",
            "cmd_son_desc": "Spielt den zuletzt gehörten Sender",
            "cmd_sonraki_desc": "Nächster Sender in der Liste",
            "cmd_onceki_desc": "Vorheriger Sender in der Liste",
            "cmd_karistir_desc": "Spielt einen zufälligen Sender",
            "cmd_uyku_desc": "Startet den Sleep-Timer",
            "cmd_gecmis_desc": "Zeigt den Song-Verlauf an",
            "cmd_favori_desc": "Sender zu Favoriten hinzufügen/entfernen",
            "cmd_favoriler_desc": "Listet Favoritensender auf",
            "cmd_kaydet_desc": "Startet die Aufnahme",
            "cmd_kayitdur_desc": "Stoppt die Aufnahme",
            "cmd_tema_desc": "Ändert das Farbschema",
            "cmd_kontrol_desc": "Überprüft Stream-URLs",
            "cmd_ekle_desc": "Fügt neuen Sender hinzu",
            "cmd_duzenle_desc": "Bearbeitet Sender",
            "cmd_sil_desc": "Löscht Sender",
            "cmd_iceaktar_desc": "Importiert Playlist",
            "cmd_bildirim_desc": "Benachrichtigungen ein/aus",
            "cmd_online_ara_desc": "Online-Suche über RadioBrowser",
            "cmd_online_ekle_desc": "Fügt Online-Sender hinzu",
            "cmd_dil_desc": "Ändert die Anwendungssprache",
            "cmd_listele_hint": "Zeigt standardmäßig die ersten 50 an. Benutzerdefiniert: listele -n NUMMER · Alle: listele --hepsi",
            "msg_not_playing": "Radio spielt nicht!",

            "msg_already_recording": "Aufnahme läuft bereits!",
            "msg_recording_started": "Aufnahme gestartet: {file}",
            "msg_recording_failed": "Aufnahme konnte nicht gestartet werden: {error}",
            "msg_no_active_record": "Keine aktive Aufnahme.",
            "msg_recording_stopped": "Aufnahme gestoppt. Gespeichert unter: {path}",
            "msg_recording_stopped_simple": "Aufnahme gestoppt.",
            "msg_playing": "Spielt: {name}",
            "msg_stop_playing": "Wiedergabe gestoppt.",
            "msg_vol_set": "Lautstärke eingestellt auf: {vol}%",
            "msg_no_last_station": "Kein Eintrag für den zuletzt gespielten Sender.",
            "msg_last_station_missing": "Zuletzt gespielter Sender nicht mehr gefunden.",
            "msg_need_list": "Bitte erstellen Sie zuerst eine Liste.",
            "msg_no_playing_station": "Kein Sender wird gerade gespielt.",
            "msg_station_not_in_list": "Aktueller Sender nicht in der Liste gefunden.",
            "msg_no_match": "Kein Sender gefunden.",
            "msg_sleep_cancel": "Sleep-Timer abgebrochen.",
            "msg_no_sleep": "Kein aktiver Sleep-Timer.",
            "msg_sleep_set": "Sleep-Timer eingestellt: stoppt in {min} Minuten.",
            "msg_sleep_done": "Sleep-Timer abgelaufen, Wiedergabe gestoppt.",
            "msg_no_history": "Noch kein Song-Verlauf.",
            "msg_recent_songs": "Zuletzt gespielte Songs:",
            "msg_fav_added": "Zu Favoriten hinzugefügt: {name}",
            "msg_fav_removed": "Aus Favoriten entfernt: {name}",
            "msg_station_not_found": "Sender nicht gefunden.",
            "msg_custom_only": "Nur eigene Sender können bearbeitet werden.",
            "msg_station_updated": "Sender aktualisiert.",
            "msg_station_deleted": "Sender gelöscht: {id}",
            "msg_station_added": "Sender hinzugefügt: {name}",
            "msg_import_success": "{count} Sender importiert.",
            "msg_import_fail": "Fehler beim Importieren.",
            "msg_notify_on": "Benachrichtigungen aktiviert.",
            "msg_notify_off": "Benachrichtigungen deaktiviert.",
            "msg_searching": "Suchen...",
            "msg_search_results": "Online-Suchergebnisse",
            "msg_online_add_hint": "Hinzufügen mit: online-ekle -n <no>",
            "msg_checking": "{count} Sender werden geprüft...",
            "msg_check_done": "Prüfung abgeschlossen: {success}/{total} aktiv.",
            "msg_active": "AKTIV",
            "msg_failed": "FEHLGESCHLAGEN",
            "msg_error": "FEHLER"
        },
        "fr": {
            "app_title": "Lecteur Radio FM Terminal - Global & Local",
            "connecting": "Connexion:",
            "now_playing": "En cours",
            "station": "Station",
            "country": "Pays",
            "genre": "Genre",
            "song": "Chanson",
            "volume": "Volume",
            "recording": "ENREGISTREMENT",
            "no_stations": "Aucune station trouvée.",
            "total_stations": "Total de {count} stations listées.",
            "welcome_msg": "Tapez 'help' pour les commandes, 'exit' pour quitter.",
            "unknown_command": "Commande inconnue : '{cmd}'. Tapez 'help' pour l'aide.",
            "error_executing": "Erreur lors de l'exécution de la commande : {error}",
            "shell_error": "Erreur de shell : {error}",
            "help_title": "LISTE DES COMMANDES",
            "cat_listing": "LISTE DES STATIONS",
            "cat_playback": "LECTURE",
            "cat_recording": "ENREGISTREMENT",
            "cat_management": "GESTION",
            "cat_other": "AUTRE",
            "cat_general": "GÉNÉRAL",
            "help_general": "help / ?            - Afficher ce menu d'aide",
            "exit_general": "exit / q / quit     - Quitter l'application",
            "stopped": "radio arrêtée",
            "waiting_song": "en attente des infos sur la chanson",
            "lang_select_title": "SÉLECTION DE LA LANGUE",
            "lang_select_msg": "Veuillez sélectionner votre langue :",
            "lang_updated": "Langue mise à jour : {lang}",
            "sys_info_title": "Informations Système",
            "sys_os": "Système d'Exploitation",
            "sys_python": "Version Python",
            "sys_cpu": "Utilisation CPU",
            "sys_ram": "RAM Système",
            "sys_total_mem": "Utilisation Totale",
            "stats_total_time": "Temps d'écoute total",
            "stats_total_sessions": "Total des sessions",
            "stats_top_title": "Top 10 Stations",
            "stats_no_data": "Pas encore de statistiques.",
            "id": "ID",
            "name": "Nom de la Station",
            "fav": "Fav",
            "no": "N°",
            "cmd_listele_desc": "Liste toutes les stations de radio",
            "cmd_turkiye_desc": "Liste les stations turques",
            "cmd_ulkeler_desc": "Liste les pays disponibles",
            "cmd_ulke_desc": "Liste les stations d'un pays spécifique",
            "cmd_turler_desc": "Liste les genres musicaux disponibles",
            "cmd_tur_desc": "Liste les stations d'un genre spécifique",
            "cmd_ara_desc": "Recherche de stations (nom, pays ou genre)",
            "cmd_istatistik_desc": "Affiche les statistiques d'écoute",
            "cmd_durum_desc": "Affiche l'état de lecture actuel",
            "cmd_sistem_desc": "Affiche les infos système et RAM",
            "cmd_temizle_desc": "Efface l'écran du terminal",
            "cmd_cal_desc": "Joue une station par ID ou index",
            "cmd_durdur_desc": "Arrête la lecture",
            "cmd_ses_desc": "Modifie le volume",
            "cmd_son_desc": "Joue la dernière station écoutée",
            "cmd_sonraki_desc": "Station suivante dans la liste",
            "cmd_onceki_desc": "Station précédente dans la liste",
            "cmd_karistir_desc": "Joue une station aléatoire",
            "cmd_uyku_desc": "Démarre la minuterie de mise en veille",
            "cmd_gecmis_desc": "Affiche l'historique des chansons",
            "cmd_favori_desc": "Ajoute/supprime une station des favoris",
            "cmd_favoriler_desc": "Liste les stations favorites",
            "cmd_kaydet_desc": "Démarre l'enregistrement",
            "cmd_kayitdur_desc": "Arrête l'enregistrement",
            "cmd_tema_desc": "Modifie le thème",
            "cmd_kontrol_desc": "Vérifie les URLs",
            "cmd_ekle_desc": "Ajoute une station",
            "cmd_duzenle_desc": "Modifie une station",
            "cmd_sil_desc": "Supprime une station",
            "cmd_iceaktar_desc": "Importe une playlist",
            "cmd_bildirim_desc": "Notifications on/off",
            "cmd_online_ara_desc": "Recherche en ligne via RadioBrowser",
            "cmd_online_ekle_desc": "Ajoute une station en ligne",
            "cmd_dil_desc": "Modifie la langue",
            "cmd_listele_hint": "Affiche les 50 premiers par défaut. Personnalisé : listele -n NOMBRE · Tous : listele --hepsi",
            "msg_not_playing": "La radio ne joue pas !",
            "msg_already_recording": "Enregistrement déjà en cours !",
            "msg_recording_started": "Enregistrement commencé : {file}",
            "msg_recording_failed": "Impossible de démarrer l'enregistrement : {error}",
            "msg_no_active_record": "Aucun enregistrement actif.",
            "msg_recording_stopped": "Enregistrement arrêté. Enregistré sous : {path}",
            "msg_recording_stopped_simple": "Enregistrement arrêté.",
            "msg_playing": "Lecture de : {name}",
            "msg_stop_playing": "Lecture arrêtée.",
            "msg_vol_set": "Volume réglé à : {vol}%",
            "msg_no_last_station": "Aucun enregistrement de la dernière station.",
            "msg_last_station_missing": "La dernière station n'existe plus.",
            "msg_need_list": "Veuillez d'abord créer une liste.",
            "msg_no_playing_station": "Aucune station en cours de lecture.",
            "msg_station_not_in_list": "Station non trouvée dans la liste.",
            "msg_no_match": "Aucune station trouvée.",
            "msg_sleep_cancel": "Minuterie annulée.",
            "msg_no_sleep": "Pas de minuterie active.",
            "msg_sleep_set": "Minuterie réglée : s'arrêtera dans {min} minutes.",
            "msg_sleep_done": "Minuterie terminée, lecture arrêtée.",
            "msg_no_history": "Pas encore d'historique.",
            "msg_recent_songs": "Chansons récentes :",
            "msg_fav_added": "Ajouté aux favoris : {name}",
            "msg_fav_removed": "Retiré des favoris : {name}",
            "msg_station_not_found": "Station non trouvée.",
            "msg_custom_only": "Seules les stations personnalisées peuvent être modifiées.",
            "msg_station_updated": "Station mise à jour.",
            "msg_station_deleted": "Station supprimée : {id}",
            "msg_station_added": "Station ajoutée : {name}",
            "msg_import_success": "{count} stations importées.",
            "msg_import_fail": "Échec de l'importation.",
            "msg_notify_on": "Notifications activées.",
            "msg_notify_off": "Notifications désactivées.",
            "msg_searching": "Recherche...",
            "msg_search_results": "Résultats de recherche en ligne",
            "msg_online_add_hint": "Ajouter avec : online-ekle -n <no>",
            "msg_checking": "Vérification de {count} stations...",
            "msg_check_done": "Vérification terminée : {success}/{total} actives.",
            "msg_active": "ACTIF",
            "msg_failed": "ÉCHEC",
            "msg_error": "ERREUR"
        },
        "it": {
            "app_title": "Lettore Radio FM da Terminale - Globale & Locale",
            "connecting": "Connessione:",
            "now_playing": "In riproduzione",
            "station": "Stazione",
            "country": "Paese",
            "genre": "Genere",
            "song": "Canzone",
            "volume": "Volume",
            "recording": "REGISTRAZIONE",
            "no_stations": "Nessuna stazione trovata.",
            "total_stations": "Totale {count} stazioni elencate.",
            "welcome_msg": "Digita 'help' per i comandi, 'exit' per uscire.",
            "unknown_command": "Comando sconosciuto: '{cmd}'. Digita 'help' per aiuto.",
            "error_executing": "Errore durante l'esecuzione del comando: {error}",
            "shell_error": "Errore shell: {error}",
            "help_title": "ELENCO COMANDI",
            "cat_listing": "ELENCO STAZIONI",
            "cat_playback": "RIPRODUZIONE",
            "cat_recording": "REGISTRAZIONE",
            "cat_management": "GESTIONE",
            "cat_other": "ALTRO",
            "cat_general": "GENERALE",
            "help_general": "help / ?            - Mostra questo menu di aiuto",
            "exit_general": "exit / q / quit     - Esci dall'applicazione",
            "stopped": "radio fermata",
            "waiting_song": "in attesa di informazioni sul brano",
            "lang_select_title": "SELEZIONE DELLA LINGUA",
            "lang_select_msg": "Seleziona la tua lingua:",
            "lang_updated": "Lingua aggiornata a: {lang}",
            "sys_info_title": "Informazioni di Sistema",
            "sys_os": "Sistema Operativo",
            "sys_python": "Versione Python",
            "sys_cpu": "Utilizzo CPU",
            "sys_ram": "RAM di Sistema",
            "sys_total_mem": "Utilizzo Totale",
            "stats_total_time": "Tempo di ascolto totale",
            "stats_total_sessions": "Sessioni totali",
            "stats_top_title": "Top 10 Stazioni",
            "stats_no_data": "Ancora nessuna statistica.",
            "id": "ID",
            "name": "Nome Stazione",
            "fav": "Fav",
            "no": "N°",
            "cmd_listele_desc": "Elenca tutte le stazioni radio",
            "cmd_turkiye_desc": "Elenca le stazioni radio turche",
            "cmd_ulkeler_desc": "Elenca i paesi disponibili",
            "cmd_ulke_desc": "Elenca le stazioni di un paese specifico",
            "cmd_turler_desc": "Elenca i generi musicali disponibili",
            "cmd_tur_desc": "Elenca le stazioni di un genere specifico",
            "cmd_ara_desc": "Cerca stazioni (nome, paese o genere)",
            "cmd_istatistik_desc": "Mostra le statistiche di ascolto",
            "cmd_durum_desc": "Mostra lo stato di riproduzione attuale",
            "cmd_sistem_desc": "Mostra info sistema e RAM",
            "cmd_temizle_desc": "Pulisce lo schermo del terminale",
            "cmd_cal_desc": "Riproduce una stazione per ID o indice",
            "cmd_durdur_desc": "Ferma la riproduzione",
            "cmd_ses_desc": "Modifica il volume",
            "cmd_son_desc": "Riproduce l'ultima stazione ascoltata",
            "cmd_sonraki_desc": "Stazione successiva nella lista",
            "cmd_onceki_desc": "Stazione precedente nella lista",
            "cmd_karistir_desc": "Riproduce una stazione casuale",
            "cmd_uyku_desc": "Avvia il timer di spegnimento",
            "cmd_gecmis_desc": "Mostra la cronologia dei brani",
            "cmd_favori_desc": "Aggiunge/rimuove stazione ai preferiti",
            "cmd_favoriler_desc": "Elenca le stazioni preferite",
            "cmd_kaydet_desc": "Inizia la registrazione",
            "cmd_kayitdur_desc": "Ferma la registrazione",
            "cmd_tema_desc": "Cambia il tema",
            "cmd_kontrol_desc": "Controlla gli URL",
            "cmd_ekle_desc": "Aggiunge una stazione",
            "cmd_duzenle_desc": "Modifica una stazione",
            "cmd_sil_desc": "Elimina una stazione",
            "cmd_iceaktar_desc": "Importa una playlist",
            "cmd_bildirim_desc": "Notifiche on/off",
            "cmd_online_ara_desc": "Ricerca online via RadioBrowser",
            "cmd_online_ekle_desc": "Aggiunge una stazione online",
            "cmd_dil_desc": "Cambia la lingua",
            "cmd_listele_hint": "Mostra i primi 50 per impostazione predefinita. Personalizzato: listele -n NUMERO · Tutti: listele --hepsi",
            "msg_not_playing": "La radio non sta suonando!",
            "msg_already_recording": "Registrazione già in corso!",
            "msg_recording_started": "Registrazione iniziata: {file}",
            "msg_recording_failed": "Impossibile avviare la registrazione: {error}",
            "msg_no_active_record": "Nessuna registrazione attiva.",
            "msg_recording_stopped": "Registrazione interrotta. Salvata in: {path}",
            "msg_recording_stopped_simple": "Registrazione interrotta.",
            "msg_playing": "In riproduzione: {name}",
            "msg_stop_playing": "Riproduzione interrotta.",
            "msg_vol_set": "Volume impostato a: {vol}%",
            "msg_no_last_station": "Nessuna stazione riprodotta di recente.",
            "msg_last_station_missing": "L'ultima stazione non esiste più.",
            "msg_need_list": "Per favore crea prima una lista.",
            "msg_no_playing_station": "Nessuna stazione in riproduzione.",
            "msg_station_not_in_list": "Stazione non trovata nella lista.",
            "msg_no_match": "Nessuna stazione trovata.",
            "msg_sleep_cancel": "Timer di spegnimento annullato.",
            "msg_no_sleep": "Nessun timer attivo.",
            "msg_sleep_set": "Timer impostato: si fermerà tra {min} minuti.",
            "msg_sleep_done": "Timer terminato, riproduzione interrotta.",
            "msg_no_history": "Cronologia brani vuota.",
            "msg_recent_songs": "Brani recenti:",
            "msg_fav_added": "Aggiunto ai preferiti: {name}",
            "msg_fav_removed": "Rimosso dai preferiti: {name}",
            "msg_station_not_found": "Stazione non trovata.",
            "msg_custom_only": "Solo le stazioni personalizzate possono essere modificate.",
            "msg_station_updated": "Stazione aggiornata.",
            "msg_station_deleted": "Stazione eliminata: {id}",
            "msg_station_added": "Stazione aggiunta: {name}",
            "msg_import_success": "{count} stazioni importate.",
            "msg_import_fail": "Importazione fallita.",
            "msg_notify_on": "Notifiche desktop attivate.",
            "msg_notify_off": "Notifiche desktop disattivate.",
            "msg_searching": "Ricerca in corso...",
            "msg_search_results": "Risultati della ricerca online",
            "msg_online_add_hint": "Aggiungi con: online-ekle -n <no>",
            "msg_checking": "Controllo di {count} stazioni...",
            "msg_check_done": "Controllo completato: {success}/{total} attive.",
            "msg_active": "ATTIVO",
            "msg_failed": "FALLITO",
            "msg_error": "ERRORE"
        }
    }

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(LocalizationService, cls).__new__(cls)
            cls._instance.current_lang = "tr"
        return cls._instance

    def set_language(self, lang: str):
        if lang in self.LANGUAGES:
            self.current_lang = lang

    def get(self, key: str, **kwargs) -> str:
        lang_strings = self.STRINGS.get(self.current_lang, self.STRINGS["en"])
        text = lang_strings.get(key, self.STRINGS["en"].get(key, key))
        if kwargs:
            try:
                return text.format(**kwargs)
            except Exception:
                return text
        return text

# Global instance
L = LocalizationService()
